apiVersion: v1
kind: Service
metadata:
  name: dat-redis-service
  labels:
    app:
      dat-redis
spec:
  selector:
    app: dat-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379